# Project configuration for SonarQube
sonar.projectKey=Gwendal-Ferlin_MSPR502_BDD_Python
sonar.projectName=MSPR502_BDD_Python
sonar.organization=gwendal-ferlin

# Path to the source and test directories
sonar.sources=api
sonar.tests=tests

# Language configurations
sonar.language=py
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

# Exclude generated, compiled, or dependency files
sonar.exclusions=**/__pycache__/**, **/*.pyc, .venv/**, .venv_temp/**, tests/**, **/__tests__/**, coverage/**
